const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),{spawn}=require('node:child_process'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const products=[{id:'trinity',published:true,free:true,coming_soon:false,price_label:'Free'}, {id:'ironglass',published:true,free:false,coming_soon:false,price_label:'$33',buy_url:'https://youngress.lemonsqueezy.com/buy/test-iron?foo=bar'}, {id:'air',published:true,free:false,coming_soon:false,price_label:'$30',buy_url:'https://youngress.lemonsqueezy.com/buy/test-air'}];
const pause=ms=>new Promise(r=>setTimeout(r,ms));let browser,ws,server,profile;
(async()=>{
 server=http.createServer((req,res)=>{const name=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));const file=name.endsWith('/')?path.join(name,'index.html'):name;try{res.setHeader('Content-Type',{'.html':'text/html','.js':'text/javascript','.png':'image/png','.jpg':'image/jpeg'}[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.writeHead(404);res.end('Not found')}}).listen(0,'127.0.0.1');
 await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 profile=fs.mkdtempSync('/tmp/checkout-chromium-');browser=spawn('/usr/bin/chromium',['--headless','--no-sandbox','--disable-gpu','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:'ignore'});
 let port;for(let i=0;i<100;i++){try{port=fs.readFileSync(path.join(profile,'DevToolsActivePort'),'utf8').split('\n')[0];break}catch{await pause(100)}}assert(port,'Chromium did not start');
 const targets=await(await fetch('http://127.0.0.1:'+port+'/json')).json();ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve);ws.addEventListener('error',reject)});
 const pending=new Map();let id=0;const exceptions=[];ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')exceptions.push(m.params.exceptionDetails)});
 const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))});const js=async(expression)=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});assert(!r.exceptionDetails,JSON.stringify(r.exceptionDetails));return r.result.value};
 await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});
 await call('Page.addScriptToEvaluateOnNewDocument',{source:`const nativeFetch=window.fetch;const fixtureProducts=${JSON.stringify(products)};const fixture=new URLSearchParams(location.search).get('fixture');
 if(fixture==='free')fixtureProducts.forEach(p=>{p.free=true;p.price_label='Free';p.buy_url=null});
 if(fixture==='unpublished')fixtureProducts[1].published=false;if(fixture==='comingsoon')fixtureProducts[1].coming_soon=true;if(fixture==='wrongprice')fixtureProducts[1].price_label='$29';if(fixture==='missing')fixtureProducts.splice(1,1);
 const invalidUrls={invalid:'https://youngress.lemonsqueezy.com.evil.example/buy/test',http:'http://youngress.lemonsqueezy.com/buy/test',credentials:'https://user:password@youngress.lemonsqueezy.com/buy/test',port:'https://youngress.lemonsqueezy.com:444/buy/test',wrongpath:'https://youngress.lemonsqueezy.com/',redirect:'https://youngress.lemonsqueezy.com/buy/test?checkout[success_url]=https://evil.example'};
 if(invalidUrls[fixture])fixtureProducts[1].buy_url=invalidUrls[fixture];
 window.fetch=(url,opts)=>String(url).includes('/rest/v1/products')?fixture==='loading'?new Promise(()=>{}):fixture==='network'?Promise.reject(Error('offline')):Promise.resolve(new Response(fixture==='malformed'?'{}':JSON.stringify(fixtureProducts),{status:fixture==='failure'?503:200})):nativeFetch(url,opts);
 window.checkoutOpened=[];if(fixture!=='sdkfailure')window.LemonSqueezy={Setup:opts=>window.checkoutEvent=opts.eventHandler,Url:{Open:url=>window.checkoutOpened.push(url)}};else{const append=Element.prototype.append;Element.prototype.append=function(el){if(el.src?.includes('/js/lemon.js'))queueMicrotask(()=>el.onerror());else append.call(this,el)}}`});
 const navigate=async url=>{await call('Page.navigate',{url:base+url});await pause(250)};const disabled=()=>js(`document.getElementById('pay-button')?.disabled===true`);
 await navigate('/?fixture=free');assert.deepEqual(await js(`[...document.querySelectorAll('[data-price]')].map(e=>e.textContent)`),['$33','$30','$33','$30'],'Approved paid prices must survive stale free catalog');
 assert(await js(`[...document.querySelectorAll('[data-buy="ironglass"]')].every(a=>a.getAttribute('href')==='checkout.html?product=ironglass'&&a.textContent==='Buy for $33')`),'IRON & GLASS should use website checkout');
 assert(await js(`[...document.querySelectorAll('[data-buy="air"]')].every(a=>a.getAttribute('href')==='checkout.html?product=air'&&a.textContent==='Buy for $30')`),'AIR should use website checkout');
 assert(await js(`[...document.querySelectorAll('[data-buy="trinity"]')].every(a=>a.getAttribute('href')==='#hub'&&/free/i.test(a.textContent))`),'TRINITY stays free through Hub');
 await navigate('/checkout.html?product=ironglass');assert.equal(await js(`document.getElementById('product-name')?.textContent`),'IRON & GLASS','Checkout should identify product');assert.equal(await js(`document.getElementById('product-price')?.textContent`),'$33');assert.equal(await disabled(),false);
 assert.match(await js('document.body.textContent'),/same email|Hub email/i,'Guest email guidance missing');if(process.env.CHECKOUT_SCREENSHOTS){const shot=await call('Page.captureScreenshot',{captureBeyondViewport:true});fs.writeFileSync('/tmp/website-checkout-desktop.png',Buffer.from(shot.data,'base64'))}await js(`document.getElementById('pay-button').click()`);
 const opened=new URL((await js('checkoutOpened'))[0]);assert.equal(opened.hostname,'youngress.lemonsqueezy.com');assert.equal(opened.searchParams.get('embed'),'1');assert.equal(opened.searchParams.get('foo'),'bar');
 await js(`checkoutEvent({event:'Checkout.Closed'})`);assert.equal(await js(`document.getElementById('checkout-complete').hidden`),true,'Closing checkout must not imply a completed payment');await js(`checkoutEvent({event:'Checkout.Success'})`);assert.equal(await js(`document.getElementById('checkout-complete').hidden`),false);assert.match(await js(`document.getElementById('checkout-complete').textContent`),/confirm|verif|sync|processing/i);assert.equal(await js(`document.querySelector('#checkout-complete a').getAttribute('href')`),'./#hub');assert.equal(await disabled(),true,'Completion prevents duplicate purchase');
 await navigate('/checkout.html?product=air');assert.equal(await js(`document.getElementById('product-price').textContent`),'$30');assert.equal(await disabled(),false);await js(`document.getElementById('pay-button').click()`);assert((await js('checkoutOpened'))[0].includes('/buy/test-air'));
 for(const fixture of ['free','unpublished','comingsoon','wrongprice','missing','invalid','http','credentials','port','wrongpath','redirect','failure','network','malformed','loading']){await navigate('/checkout.html?product=ironglass&fixture='+fixture);assert.equal(await disabled(),true,'Unsafe checkout enabled for '+fixture);assert.equal(await js(`document.getElementById('product-price').textContent`),'$33');assert(await js(`document.getElementById('checkout-status').textContent.length>10`),'Missing status for '+fixture);await js(`document.getElementById('pay-button').click()`);assert.deepEqual(await js('checkoutOpened'),[],'Unsafe checkout opened for '+fixture)}
 for(const product of ['unknown','trinity','constructor','__proto__','']){await navigate('/checkout.html?product='+product);assert.equal(await disabled(),true,'Nonpaid/unknown checkout enabled: '+product)}
 await navigate('/checkout.html?product=trinity');assert.equal(await js(`document.getElementById('checkout-free')?.getAttribute('href')`),'./#hub','Free checkout should link Hub downloads');assert.equal(await js(`document.getElementById('checkout-free')?.hidden`),false);
 await navigate('/checkout.html?product=ironglass&success=true&payment_status=paid');assert.equal(await js(`document.getElementById('checkout-complete').hidden`),true,'Query parameters must not declare ownership');
 await navigate('/checkout.html?product=ironglass&fixture=sdkfailure');await js(`document.getElementById('pay-button').click()`);await pause(50);assert.match(await js(`document.getElementById('checkout-status').textContent`),/secure checkout|try again/i);assert(await js(`document.getElementById('checkout-fallback').href.startsWith('https://youngress.lemonsqueezy.com/buy/')`),'SDK failure should offer validated hosted checkout');
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});for(const url of ['/','/checkout.html?product=ironglass']){await navigate(url);assert(await js('document.documentElement.scrollWidth<=innerWidth+1'),'Mobile horizontal overflow: '+url)}
 if(process.env.CHECKOUT_SCREENSHOTS){const shot=await call('Page.captureScreenshot',{captureBeyondViewport:true});fs.writeFileSync('/tmp/website-checkout-mobile.png',Buffer.from(shot.data,'base64'))}
 assert.equal(exceptions.length,0,'JavaScript exceptions: '+JSON.stringify(exceptions));console.log('PASS: approved website pricing/CTAs, free TRINITY, both paid overlays, 15 unavailable/security cases, unknown products, query spoofing, completion, SDK fallback and 390px layout. Catalog and payment SDK mocked; no purchases made.');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>{ws?.close();browser?.kill();server?.close()});
setTimeout(()=>{console.error('Browser check timed out');process.exit(1)},60000).unref();
